# Site settings
title: wwwer.org
tag_text: wwwer.org
description: Simple service for redirections from non-www to www domains

# Build settings
markdown: kramdown
exclude: ["README.md"]
host: 0.0.0.0
sass:
  style: compressed
